# Generated by Django 2.2.4 on 2019-08-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('title', models.CharField(max_length=100, verbose_name='Название статьи')),
                ('description', models.CharField(max_length=500, null=True, verbose_name='Краткое описание (500 символов)')),
                ('content', models.TextField(verbose_name='Текст статьи (вводить сохраняя теги)')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('img', models.ImageField(null=True, upload_to='images', verbose_name='Изображение статьи')),
                ('alt_image', models.CharField(max_length=30, null=True, verbose_name='Alt для изображения статьи')),
                ('tag', models.CharField(max_length=20, null=True, verbose_name='Тег статьи (не более одного)')),
                ('slug', models.SlugField(max_length=250, primary_key=True, serialize=False, verbose_name='Красивая ссылка латиницей')),
                ('author', models.CharField(max_length=20, null=True, verbose_name='Автор статьи')),
            ],
            options={
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
