# Generated by Django 2.2.4 on 2019-08-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='meta_descr',
            field=models.CharField(max_length=300, null=True, verbose_name='Description для meta'),
        ),
    ]
