# Generated by Django 2.2.4 on 2019-08-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_articles_meta_descr'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='meta_titile',
            field=models.CharField(max_length=300, null=True, verbose_name='Title для meta'),
        ),
    ]
