# Generated by Django 2.1.4 on 2019-10-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191026_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articletags',
            name='id',
        ),
        migrations.AddField(
            model_name='articletags',
            name='slug',
            field=models.SlugField(default='', max_length=250, primary_key=True, serialize=False, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='articletags',
            name='title',
            field=models.CharField(max_length=20, null=True, verbose_name='Тег'),
        ),
    ]
