# Generated by Django 2.1.4 on 2019-10-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191026_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletags',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='articles',
            name='tag_new',
        ),
        migrations.AddField(
            model_name='articles',
            name='tag_new',
            field=models.ManyToManyField(default='', to='main.ArticleTags', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='articletags',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True, verbose_name='Транслит'),
        ),
    ]
