# Generated by Django 2.1.4 on 2019-10-26 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191026_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='tag_new',
        ),
        migrations.DeleteModel(
            name='ArticleTags',
        ),
    ]
