# Generated by Django 2.1.4 on 2019-10-26 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_articletags'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='tag_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ArticleTags'),
        ),
    ]
