# Generated by Django 2.1.4 on 2019-10-28 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_articletags_rgb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='tag',
        ),
    ]
