# Generated by Django 2.1.4 on 2019-10-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
    ]
